[package]
name = "swtchr"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
gtk4-layer-shell = "0.2.0"

[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
