[package]
name = "swtchr"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image", "svg"] }

[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
